apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-frontend
  namespace: backend
spec:
  podSelector: {}  # Apply to all pods in this namespace
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: allowed-namespace # No matching label for frontend namespace
