services:
  backend:
    build: ./backend
    ports:
      - 8080:8080  
    depends_on:
      - db
    restart: always
    environment: 
      - MYSQL_PASSWORD = ${MYSQL_PASSWORD}
    networks:
      - my-network

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: always
    networks:
      - my-network
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - my-network

networks:
  my-network:
    driver: bridge