apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
spec:
  selector:
    name: app1 # <target label> 
  ports:
   - port: 8004
     targetPort: 5432
     protocol: TCP
     name: db
   - port: 9111 
     targetPort: 9216
     protocol: TCP
     name: exporter