apiVersion: v1
kind: Service
metadata:
  name: test-nodeport
spec:
  type: NodePort
  selector:
   app: test
  ports:
   - port: 3000
     targetPort: 3000
     nodePort: 30100 #(30000-32767)
     protocol: TCP