apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica-set
  labels:
    app: nginx-rs
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-pod
      labels:
        app: app1
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  selector:
    matchLabels:
      type: front-end